# Permalinks
permalink:           pretty

# Setup
title:               MDS Validator
url:                 https://www.validator.com.au

# About/contact
author:
  name:              'Strategic Data'
  email:             'support@validator.com.au'

exclude: [node_modules,vendor,src,gulpfile.js,bower_components,bower.json,README.md,static,package.json,'*.sh',nginx.d]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
source:      _source
destination: _site
